const wordsData = [
  {
    category: 'Animals',
    words: [
      'Elephant',
      'Kangaroo',
      'Dolphin',
      'Giraffe',
      'Penguin',
      'Crocodile',
      'Flamingo',
      'Hedgehog',
      'Peacock',
      'Octopus',
    ],
  },
  {
    category: 'Fruits',
    words: [
      'Banana',
      'Watermelon',
      'Pineapple',
      'Strawberry',
      'Blueberry',
      'Kiwi',
      'Pomegranate',
      'Mango',
      'Avocado',
      'Papaya',
    ],
  },
  {
    category: 'Colors',
    words: [
      'Red',
      'Blue',
      'Green',
      'Yellow',
      'Purple',
      'Orange',
      'Violet',
      'Indigo',
      'Crimson',
      'Scarlet',
    ],
  },
  {
    category: 'Sports',
    words: [
      'Soccer',
      'Baseball',
      'Basketball',
      'Cricket',
      'Tennis',
      'Badminton',
      'Hockey',
      'Volleyball',
      'Archery',
      'Skiing',
    ],
  },
  {
    category: 'Countries',
    words: [
      'Australia',
      'Brazil',
      'Canada',
      'Denmark',
      'Egypt',
      'Finland',
      'Germany',
      'India',
      'Japan',
      'Kenya',
    ],
  },
  {
    category: 'Space',
    words: [
      'Planet',
      'Galaxy',
      'Meteor',
      'Comet',
      'Nebula',
      'Orbit',
      'Telescope',
      'Universe',
      'Blackhole',
      'Asteroid',
    ],
  },
  {
    category: 'Foods',
    words: [
      'Pizza',
      'Burger',
      'Pasta',
      'Sushi',
      'Pancake',
      'Tacos',
      'Curry',
      'Sandwich',
      'Salad',
      'Chocolate',
    ],
  },
  {
    category: 'Professions',
    words: [
      'Doctor',
      'Engineer',
      'Teacher',
      'Lawyer',
      'Pilot',
      'Scientist',
      'Chef',
      'Farmer',
      'Artist',
      'Plumber',
    ],
  },
];

export function getRandomWords() {
  const randomIndex = Math.floor(Math.random() * wordsData.length);
  return wordsData[randomIndex];
}
